apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ms-middleware-signcrypt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /host_mnt/C/home/devopsa/microservicios/ms-middleware-signcrypt/logs
    type: Directory
