info:
  version: 1.0.0
  date: 2025-04-22
  stage: development
  author: Wilson Castro L..
  email: wcastro@banred.fin.ec
  description: Microservicio Mock Server OCSP
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 100000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
    provider-name: SunJCE
    password: Sk/uXJSiwA8Ol2F59NnMBj9k7NYviJ06OOCz3DO7KU8ktqqHBnkt+EkEgJHu4133
    skip-property-sources:
      - org.springframework.boot.env.RandomValuePropertySource
      - org.springframework.boot.ansi.AnsiPropertySource

server:
  ssl:
    enabled: false  # FUERZA HTTP
  port: 8085
  address: 0.0.0.0
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: never
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  undertow:
    threads:
      io: 10
      worker: 256
    allow-encoded-slash: false
    always-set-keep-alive: true
    decode-url: true
    eager-filter-init: true
    max-cookies: 200
    max-headers: 200
    max-http-post-size: 10MB
    preserve-path-on-forward: false
    url-charset: UTF-8


logging:
  level:
    org.springframework.security: DEBUG
    com.ulisesbocchio.jasyptspringboot: DEBUG  # Logs decryption attempts
    org.jasypt: DEBUG  # Logs Jasypt core operations
