info:
  version: 1.0.0
  date: 2025-09-05
  stage: development
  autor: Daniel Arcos, Wilson Castro
  email: darcos@banred.fin.ec, wcastro@banred.fin.ec
  description: ms-middleware-signcrypt

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64
    password: KcNcOTIseNsxSnD+PcHWp5H6K08ZUqGMIf7WggPE5TegDU0O9ruF+2Bn4CJW2MFF6sKjc3oDlAEy/JQiY+1Nqg==
    skip-property-sources:
      - org.springframework.boot.env.RandomValuePropertySource
      - org.springframework.boot.ansi.AnsiPropertySource

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api
  compression:
    enabled: true
  error:
    include-message: never
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  address: ${SERVER_ADDRESS}
  undertow:
    threads:
      io: 10
      worker: 256
    allow-encoded-slash: false
    always-set-keep-alive: true
    decode-url: true
    eager-filter-init: true
    max-cookies: 200
    max-headers: 200
    max-http-post-size: 10MB
    preserve-path-on-forward: false
    url-charset: UTF-8

spring:
  main:
    log-startup-info: true
    banner-mode: console
  thymeleaf:
    enabled: false
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-date-keys-as-timestamps: false
    time-zone: GMT-5
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.banred: DEBUG
    org.springframework.security: DEBUG
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/app.%d{yyyy-MM-dd}.log
      max-history: 7
      total-size-cap: 1GB

camel:
  component:
    servlet:
      enabled: true
    saga:
      enabled: false
  springboot:
    main-run-controller: true

microservice:
  parameters:
    REDIS_PORT: ${REDIS_PORT}
    REDIS_USERNAME: ${REDIS_USERNAME}
    REDIS_PASSWORD: ${REDIS_PASSWORD}
    REDIS_HOSTNAME: ${REDIS_HOSTNAME}
    RUTA_CONFIG_XML: ${RUTA_CONFIG_XML}
    RUTA_CRL: ${RUTA_CRL}
    RUTA_RSA: ${RUTA_CRL}
    EXPIRY_SECONDS: ${EXPIRY_SECONDS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    show-details: always
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

mtls:
  certs:
    valid: false
  ocsp:
    enabled: false
    soft-fail: true
    timeout: 5000
